### ISSUE TITLE
Library doesn't allow empty string label

### ISSUE THREAD

**Issue by jakubneubauer** [prom-client-net/prom-client#158]
Empty string labels are allowed by Prometheus, however the client library throws exception on it.
The check for null was there from beginning, but check for empty string was added in following commit, breaking backward compatibility, by the way:
commit 5f1dd1e466feb9851539a277d643f9c747315b88
Author: sanych-sun
Date: 12/15/20, 8:39 AM
Performance tweaks

I submitted pull request to fix it and I'm kindly asking to accept it. Thank you
https://github.com/prom-client-net/prom-client/pull/157

**Comment by sanych-sun** [comment]
Good catch! Thank you for your feedback and PR.

I've added some comments under your PR, please update it and we will get it merged.

**Comment by jakubneubauer** [comment]
Your comments resolved. Can I kindly ask if you could release new version with the changes? It is kind of blocker in our project, since production code throws many exceptions with the newer version.

**Comment by sanych-sun** [comment]
Thank you for the contribution. I've approved the PR and will merge it. Just want to add some more unit-tests, but it should not take me long.

**Comment by sanych-sun** [comment]
The changes is merged into V4 branch. @phnx47, could you please cut the v4 release?

**Comment by phnx47** [comment]
@sanych-sun Yep! I will do it today later

**Comment by phnx47** [comment]
Released: [v4.5.3](https://github.com/prom-client-net/prom-client/releases/tag/v4.5.3)

**Comment by jakubneubauer** [comment]
Thank you very much for your fast response!
