### ISSUE TITLE
CancellationTokens support in ScrapeHandler

### ISSUE THREAD

**Issue by utybo** [prom-client-net/prom-client#164]
Hi! First of all, thank you for your work on Prometheus.Client.

While migrating an application from `prometheus-net` to `Prometheus.Client`, I noticed that `prometheus-net`'s [`ICollectorRegistry`](https://github.com/prometheus-net/prometheus-net/blob/1cfbebb79719b9016284b7ded8dc5ef93e500fea/Prometheus.NetStandard/ICollectorRegistry.cs#L21) supports `CancellationToken`s, while `Prometheus.Client`'s `ScrapeHandler` [does not](https://github.com/prom-client-net/prom-client/blob/master/src/Prometheus.Client/ScrapeHandler.cs). It does not seem like the underlying `ICollector` functions support cancellation tokens either, unfortunately. Would there be a way to add such support?

**Comment by phnx47** [comment]
@utybo Thank you for the issue. I will investigate this

**Comment by phnx47** [comment]
It is planned for the next major release
