### ISSUE TITLE
Normalize default metrics 

### ISSUE THREAD

**Issue by phnx47** [prom-client-net/prom-client#189]
- Revision of current default metrics with best practices: https://prometheus.io/docs/practices/naming/
- Add new metrics if possible.

**Comment by sanych-sun** [comment]
can we add some configuration or settings to allow "legacy metric names" as this is a breaking change that will require dashboards rework on client side.

**Comment by phnx47** [comment]
@sanych-sun Good point, we have some options. I will add my ideas.
