### ISSUE TITLE
more debug info in exception message when label validation fails

### ISSUE THREAD

**Issue by cscoon** [prom-client-net/prom-client#204]
Today, when label validation fails, the exception message is "Collector with same name must have same type and same label names"

We see these messages in our logs, but the message doesn't tell us 2 important things: 1) what is the name of the metric? 2) what were the labels and values that failed validation?

We have several metrics and emit metrics at many places in our source code.  The current exception message doesn't give us the information we need to find the offending code and fix it.  This makes debugging unnecessarily long and error prone.

Suggested fix: a message name similar to - "Collector with same name must have same type and same label names.  Metric name = this_is_the_metric.  Labels = label1=valueA;label2=valueB;label3=valueC;"

**Comment by phnx47** [comment]
@cscoon I can do it this or next week. 

Also feel free to open PR, Exception from here:
https://github.com/prom-client-net/prom-client/blob/37eb36f3875d2a57fd1eb167037ece33bb3a14a9/src/Prometheus.Client/MetricFactory.cs#L706

**Comment by cscoon** [comment]
An update to the fix I suggested in my earlier post... the exception message should output the names of the labels that are attempting to be emitted (unsuccessfully) AND it should also output the names of the labels that are already output.

An example of why this would be helpful - I am currently debugging an issue where we apparently have a code path that is emitting a logging-related metric with the wrong collection of labels.  However, my error log message outputs the labels that caused the exception, and those labels appear correct.  That must mean that the incorrect collection of labels had been emitted previously.  But I don't know what those labels were, and the pod that emitted them has recycled and therefore can't be queried anymore.

**Comment by phnx47** [comment]
@cscoon I understood the problem, simple task. Need to wait when I will be free. But, It can be released faster if you raise PR, I will be appreciated.

**Comment by phnx47** [comment]
@cscoon Published: [v5.1.0](https://github.com/prom-client-net/prom-client/releases/tag/v5.1.0)
