### ISSUE TITLE
exception is thrown when labels appear in a different order

### ISSUE THREAD

**Issue by cscoon** [prom-client-net/prom-client#207]
We are receiving the exception "Collector with same name must have same type and same label names" when in fact the labels for this metric are the same.  The only difference is that the labels appear in a different order.

For example, the /metrics endpoint exposes a label like this:

`my_metric {labelA="A",labelB="B",tenant_id="blah",tenant_purpose="blah"}`

When we attempt to publish this metric, it fails:

`my_metric {tenant_id="blah",tenant_purpose="blah",labelA="A",labelB="B"}`

This is a problem because we have certain groups of labels that get appended to the metric during re-runnable methods; that process means that the label will have the same labels by the time it is ready to be emitted, but they aren't guaranteed to have been built up in the same order each time.  But by the time the metric is ready to be emitted, it has the correct set of labels attached to it.

**Comment by phnx47** [comment]
Highly recommended use same order. We will not re-order labels in library with each Inc().

I will do additional investigation how Prometheus validate same metric with different order. If it possibly will support this in library

**Comment by phnx47** [comment]
@cscoon 

Prometheus re-order labels on their side. But in this library you must use same order. 

We use array and tuple for labels. For 'Different Order' feature, it should be a dictionary. It will very expensive rewrite current implementation! 

Also I tried publish as a new metric, second metric is ignored
![image](https://user-images.githubusercontent.com/1101691/195078261-7c560779-e20d-4483-9354-6b4edb5f0fa2.png)
![image](https://user-images.githubusercontent.com/1101691/195078555-93a7c90e-7baa-498b-b146-633903e3b436.png)
