### ISSUE TITLE
Move Create[Metric] from Extensions to MetricFactory

### ISSUE THREAD

**Issue by phnx47** [prom-client-net/prom-client#212]
I have issue when methods with conversion String to Tuple cannot be used from Extensions without timestamp since v5.

Look commit: https://github.com/prom-client-net/prom-client-healthchecks/commit/ced97c89b4cfda3f2b0e32764b268855bc60474f

**Comment by sanych-sun** [comment]
You should reference namespace Prometheus.Client. for proper extension resolution. Not sure how it worked before =)

**Comment by phnx47** [comment]
@sanych-sun I checked this, doesn't work. I beleive, that some extensions better move to `MetricFactry` it is more consistency and this fix issue.
