### ISSUE TITLE
Possible race condition will yield incorrect result

### ISSUE THREAD

**Issue by Dave-French** [prom-client-net/prom-client#257]
The ThreadSafeDouble looks to have a thread safety/race condition bug in the Add method.

For the code:
`

            var lastValue = Interlocked.CompareExchange(ref _value, BitConverter.DoubleToInt64Bits(computedValue), currentValue);

            if (lastValue == currentValue)
                return;
`

The "IF" will always succeed since `currentValue` will always equal `lastValue` since the `CompareExchange` always will returns the location field (`_value`) regardless of whether the location field is updated or not.  This means that if another thread updated the `_value` after reading the `currentValue`, the CompareExchange call will fail but since the "IF" succeeds, the method returns without correctly updating the `_value` to the new value.

The [MSDN for the method](https://learn.microsoft.com/en-us/dotnet/api/system.threading.interlocked.compareexchange?view=net-7.0#system-threading-interlocked-compareexchange(system-int64@-system-int64-system-int64)) says:
`The return value of CompareExchange is the original value in location1, whether or not the exchange takes place.`

**Comment by phnx47** [comment]
@Dave-French Can you reproduce the bug? Here [ThreadSafeDouble](https://github.com/prom-client-net/prom-client/blob/main/tests/Prometheus.Client.Tests/ThreadSafeDoubleTests.cs) tests.
