### ISSUE TITLE
Implement integration with DiagnosticSource

### ISSUE THREAD

**Issue by sanych-sun** [prom-client-net/prom-client#73]
We need to propose and implement integration with [DiagnosticSource](https://github.com/dotnet/corefx/blob/d3942d4671919edb0cca6ddc1840190f524a809d/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md). This integration should provide an easy way to filter and map events into metrics. It might be done as a additional package if this makes sense.

**Comment by phnx47** [comment]
This can help: https://github.com/Chakrygin/DiagnosticsNet

**Comment by Sergey-Terekhin** [comment]
May be not `EventSource`, but `DiagnosticSource` would be more suitable for that?
These articles can help (it only in russian): 
https://habr.com/ru/company/ozontech/blog/435896/
https://habr.com/ru/company/ozontech/blog/221037/

**Comment by phnx47** [comment]
@Sergey-Terekhin Thank you!

**Comment by phnx47** [comment]
Nobody interested
